/**
 * EXODUS STRONG — MISSION CONTROL DATA CONFIG
 * ─────────────────────────────────────────────
 * This is the ONLY file you need to edit to update your dashboard.
 * It feeds every component. The template shell stays untouched so
 * you can `git pull upstream main` to get AI Monetization team improvements.
 *
 * THE NEHEMIAH PROTOCOL · 1 Kings 7:7
 * Solomon runs the Hall of Judgment.
 */

// ─── BRAND ───────────────────────────────────────────────────────────────────

export const BRAND = {
  eyebrow: "EXODUS STRONG",
  title: "Mission Control",
  subtitle: "THE NEHEMIAH PROTOCOL",
  owner: "Rob René",
  agent: "Solomon ⚔️",
  scripture: "1 Kings 7:7",
  footer: "STOP PLANNING. START EXECUTING.",
  footerAccent: "PROJECT JUBILEE.",
};

// ─── PHASE PROGRESS (maps to PhaseProgress bar) ──────────────────────────────

export const PHASES = [
  { key: "foundation", label: "Foundation" },
  { key: "compliance", label: "Compliance" },
  { key: "funnel",     label: "Funnel" },
  { key: "launch",     label: "Launch" },
  { key: "scale",      label: "Scale" },
  { key: "red-wave",   label: "Red Wave" },
  { key: "red-wave-2", label: "Wave 2" },
  { key: "moat",       label: "Moat" },
  { key: "jubilee",    label: "Jubilee" },
];

export const CURRENT_PHASE = "foundation";

// ─── ALERTS (CEO Dashboard top bar) ──────────────────────────────────────────

export const ALERTS = [
  {
    type: "red",
    message: "Gate I OPEN: FDA/FTC regulatory counsel not yet retained — blocks warm list launch and paid placements",
    area: "Compliance",
  },
  {
    type: "red",
    message: "Gate II HOLDING: AC Ascension Funnel not yet built — warm list (8,400 subs) PROTECTED until cold traffic test passes",
    area: "Funnel",
  },
  {
    type: "yellow",
    message: "Gate III: +Quantum / QE Strong branding risk unresolved — Levite flagging all QE Strong content YELLOW",
    area: "Branding",
  },
  {
    type: "green",
    message: "The Levite is LIVE on Solomon2 — compliance scanning active, all content cleared before customer delivery",
    area: "Compliance",
  },
];

// ─── CEO DASHBOARD — KPI DATA ─────────────────────────────────────────────────
// Week 1: Foundation phase — revenue is $0, we're investing and building.
// Update these numbers as actuals come in.

export const CEO_KPI = {
  // THE MONEY
  revenue:      { current: 0,    previous: 0    },
  newSales:     { count: 0,      value: 0       },
  aov:          { current: 0                    },

  // THE PIPELINE
  leads:        { current: 0,    previous: 0    },
  eventRegs:    { webinar: 0, challenge: 0, total: 0, previous: 0 },
  conversionRate: { current: 0,  previous: 0    },

  // THE HEALTH
  activeClients: {
    subscribers:   { count: 8400,  label: "Beehiiv Subscribers (PROTECTED)" },
    bookBuyers:    { count: 0,     label: "Light Code Book Buyers"           },
    subscription:  { count: 0,     label: "$60/mo Subscribers"              },
    redWaveLeads:  { count: 0,     label: "Red Wave Leads"                  },
  },
  referrals:    { current: 0,    previous: 0    },
  adSpend:      { spend: 105,    revenue: 0,    roas: 0 }, // $15/day × 7 days Phase 1

  rangeLabel: "Week 1 · March 24–30, 2026",
};

// ─── PROMOTE CHANNELS ─────────────────────────────────────────────────────────

export const PROMOTE_CHANNELS = [
  {
    name: "Cold Email",
    icon: "📧",
    color: "#2F80FF",
    leads: 0,
    eventRegs: 0,
    metrics: {
      domains: 3,
      warmupDays: 1,
      targetList: 500,
      sequenceEmails: 3,
    },
    status: "WARMING UP",
    note: "Domain warmup started Week 1. First real sends Week 4–5.",
  },
  {
    name: "Paid Ads (Laurel)",
    icon: "📱",
    color: "#7B61FF",
    leads: 0,
    eventRegs: 0,
    metrics: {
      dailySpend: 15,
      videos: 3,
      objective: "Video Views",
      targetCPV: "$0.07–$0.50",
    },
    status: "PHASE 1 ACTIVE",
    note: "Invisible list building. NOT conversions yet. $5/day × 3 videos.",
  },
  {
    name: "Red Wave (Free Media)",
    icon: "🌊",
    color: "#FF4EDB",
    leads: 0,
    eventRegs: 0,
    metrics: {
      applicationsSubmitted: 0,
      showsTargeted: 5,
      reviewUnitsShipped: 0,
      networkContactsMade: 0,
    },
    status: "LAUNCHING",
    note: "PodMatch, MatchMaker.fm registration this week. Top 5 applications out.",
  },
  {
    name: "Partnerships",
    icon: "🤝",
    color: "#10B981",
    leads: 0,
    eventRegs: 0,
    metrics: {
      activePartners: 0,
      podcastPitchesSent: 0,
      affiliatesRecruited: 0,
      commissions: 0,
    },
    status: "OUTREACH STARTING",
    note: "Jay working Red Wave outreach. Ambassador agent deploys Week 9.",
  },
];

// ─── PROFIT FUNNELS ───────────────────────────────────────────────────────────

export const PROFIT_FUNNELS = [
  {
    name: "AC Ascension Funnel",
    icon: "📖",
    type: "Cart",
    color: "#7B61FF",
    visitors: 0,
    conversions: 0,
    rate: 0,
    revenue: 0,
    status: "BUILDING",
    note: "Light Code Book ($47) → OB → OTO1 ($67 H₂) → OTO2 (device) → $60/mo sub. Zipify OCU.",
  },
  {
    name: "Warm List Launch",
    icon: "📬",
    type: "Email",
    color: "#FF4EDB",
    visitors: 8400,
    conversions: 0,
    rate: 0,
    revenue: 0,
    status: "LOCKED — GATE II",
    note: "God Algorithm → Quiz Bridge (5 emails). LOCKED until funnel proven with cold traffic.",
  },
  {
    name: "Laurel FAST Funnel",
    icon: "💬",
    type: "Messenger",
    color: "#2F80FF",
    visitors: 0,
    conversions: 0,
    rate: 0,
    revenue: 0,
    status: "PLANNED — WEEK 5",
    note: "Comment 'LIGHT' → Messenger → 9-10 exchanges → qualify. Activates when audiences hit 1K.",
  },
  {
    name: "Book-a-Call (High Ticket)",
    icon: "📞",
    type: "Call",
    color: "#10B981",
    visitors: 0,
    conversions: 0,
    rate: 0,
    revenue: 0,
    status: "PLANNED — WEEK 7",
    note: "The Centurion routes qualified DM leads to discovery calls. Target close rate >20%.",
  },
  {
    name: "$27 Challenge Guide",
    icon: "⚡",
    type: "Low-Ticket",
    color: "#F59E0B",
    visitors: 0,
    conversions: 0,
    rate: 0,
    revenue: 0,
    status: "PLANNED — MONTH 2",
    note: "40-Day Light Code Challenge. Maria Wint $27 model. Zero COGS. Alternative funnel entry.",
  },
];

// ─── AI SALES (maps to profit view aiSales section) ──────────────────────────

export const AI_SALES = {
  name: "The Centurion",
  ticketsSold: 0,
  assists: 0,
  directSales: 0,
  totalConversations: 0,
  responseTime: "—",
  revenue: 0,
  deployWeek: 7,
  note: "Deploys Week 7–8. High-ticket DM sales qualifier. GHL pipeline routing.",
};

// ─── PRODUCE / OFFERS ─────────────────────────────────────────────────────────

export const PRODUCE_OFFERS = [
  {
    name: "Light Code Book ($47)",
    icon: "📖",
    color: "#7B61FF",
    active: 0,
    capacity: null,
    completed: 0,
    satisfaction: null,
    referrals: 0,
    note: "Primary front-end. In build. The Herald generates copy. Actovision builds pages.",
  },
  {
    name: "Molecular Hydrogen OTO ($67)",
    icon: "⚗️",
    color: "#2F80FF",
    active: 0,
    capacity: null,
    completed: 0,
    satisfaction: null,
    referrals: 0,
    note: "OTO1 — Sultanic pixel optimization point. Meta Purchase event maps here.",
  },
  {
    name: "RLT Device (Founding Price)",
    icon: "💡",
    color: "#FF4EDB",
    active: 0,
    capacity: null,
    completed: 0,
    satisfaction: null,
    referrals: 0,
    note: "OTO2 — device at founding member pricing. High-ticket backend.",
  },
  {
    name: "Light Code Subscription ($60/mo)",
    icon: "🔄",
    color: "#10B981",
    active: 0,
    capacity: null,
    completed: 0,
    satisfaction: null,
    referrals: 0,
    note: "Backend subscription. Day 14 pitch to book buyers. 10% conversion target.",
  },
  {
    name: "QE Strong Patches",
    icon: "🩹",
    color: "#F59E0B",
    active: 0,
    capacity: null,
    completed: 0,
    satisfaction: null,
    referrals: 0,
    note: "YELLOW FLAG: Gate III unresolved. +Quantum branding under regulatory review.",
  },
  {
    name: "Face Mask+",
    icon: "✨",
    color: "#8B5CF6",
    active: 0,
    capacity: null,
    completed: 0,
    satisfaction: null,
    referrals: 0,
    note: "TikTok Shop pilot planned. Ambassador agent targets creators (Week 9+).",
  },
];

// ─── TWELVE TRIBES (maps to AIWorkforce) ──────────────────────────────────────

export const TWELVE_TRIBES = [
  {
    id: "the-levite",
    name: "The Levite",
    avatar: "⚖️",
    role: "Compliance Gate",
    department: "Compliance",
    departmentColor: "#10B981",
    status: "active",
    machine: "Solomon2",
    deployWeek: 1,
    currentTask: "Scanning all content — GREEN/YELLOW/RED verdicts before customer delivery",
    progress: 100,
    tasksToday: 0,
    successRate: 100,
    avgResponseTime: "<1s",
    lastAction: "Compliance gate LIVE — FastAPI + 3-agent CrewAI crew operational",
    lastActionTime: 0,
    scripture: "Numbers 1:53",
  },
  {
    id: "the-scribe",
    name: "The Scribe",
    avatar: "📜",
    role: "Email Sequence Architect",
    department: "Email",
    departmentColor: "#2F80FF",
    status: "planned",
    machine: "Solomon2",
    deployWeek: 2,
    currentTask: "Deploying Week 2 — building 4 sequences (DRAFT only, not deployed until Gate II clears)",
    progress: 0,
    tasksToday: 0,
    successRate: 0,
    avgResponseTime: "—",
    lastAction: "Pending deployment",
    lastActionTime: 0,
    scripture: "Ezra 7:6",
  },
  {
    id: "the-multiplier",
    name: "The Multiplier",
    avatar: "✖️",
    role: "Content Repurposing Engine",
    department: "Content",
    departmentColor: "#7B61FF",
    status: "planned",
    machine: "Solomon2",
    deployWeek: 2,
    currentTask: "Deploying Week 2 — 1 pillar video → 10–15 derivative assets for Carpe Diem",
    progress: 0,
    tasksToday: 0,
    successRate: 0,
    avgResponseTime: "—",
    lastAction: "Pending deployment",
    lastActionTime: 0,
    scripture: "Matthew 14:20",
  },
  {
    id: "the-merchant",
    name: "The Merchant",
    avatar: "🛒",
    role: "Cart Recovery + Upsells",
    department: "Revenue",
    departmentColor: "#FF4EDB",
    status: "planned",
    machine: "Solomon",
    deployWeek: 3,
    currentTask: "Deploying Week 3 — Shopify webhooks → CrewAI → Levite scan → Klaviyo",
    progress: 0,
    tasksToday: 0,
    successRate: 0,
    avgResponseTime: "—",
    lastAction: "Pending deployment",
    lastActionTime: 0,
    scripture: "Proverbs 31:18",
  },
  {
    id: "the-watchman",
    name: "The Watchman",
    avatar: "👁️",
    role: "Daily Intelligence Briefing",
    department: "Intelligence",
    departmentColor: "#F59E0B",
    status: "planned",
    machine: "Solomon",
    deployWeek: 3,
    currentTask: "Deploying Week 3 — daily brief at 6:00 AM, War Council every Sunday",
    progress: 0,
    tasksToday: 0,
    successRate: 0,
    avgResponseTime: "—",
    lastAction: "Pending deployment",
    lastActionTime: 0,
    scripture: "Ezekiel 33:7",
  },
  {
    id: "the-herald",
    name: "The Herald",
    avatar: "📢",
    role: "Funnel Copy Engine",
    department: "Copy",
    departmentColor: "#06B6D4",
    status: "planned",
    machine: "Solomon",
    deployWeek: 3,
    currentTask: "Deploying Week 3 — VSL, quiz, advertorial, offer stack (Sultanic + Hormozi)",
    progress: 0,
    tasksToday: 0,
    successRate: 0,
    avgResponseTime: "—",
    lastAction: "Pending deployment",
    lastActionTime: 0,
    scripture: "Isaiah 40:9",
  },
  {
    id: "the-shepherd",
    name: "The Shepherd",
    avatar: "🐑",
    role: "AI Customer Service",
    department: "Support",
    departmentColor: "#8B5CF6",
    status: "planned",
    machine: "Solomon2",
    deployWeek: 4,
    currentTask: "Deploying Week 4 — Tidio Lyro chatbot + VOC transcript analysis",
    progress: 0,
    tasksToday: 0,
    successRate: 0,
    avgResponseTime: "—",
    lastAction: "Pending deployment",
    lastActionTime: 0,
    scripture: "John 10:11",
  },
  {
    id: "the-oracle",
    name: "The Oracle",
    avatar: "🔮",
    role: "A/B Testing + CRO",
    department: "Optimization",
    departmentColor: "#EC4899",
    status: "planned",
    machine: "Solomon",
    deployWeek: 5,
    currentTask: "Deploying Weeks 5–6 — offer-level tests first, then copy-level",
    progress: 0,
    tasksToday: 0,
    successRate: 0,
    avgResponseTime: "—",
    lastAction: "Pending deployment",
    lastActionTime: 0,
    scripture: "Daniel 2:22",
  },
  {
    id: "the-trumpet",
    name: "The Trumpet",
    avatar: "🎺",
    role: "Social Content Engine",
    department: "Social",
    departmentColor: "#F97316",
    status: "planned",
    machine: "Solomon",
    deployWeek: 5,
    currentTask: "Deploying Weeks 5–6 — daily content feed for Carpe Diem queue",
    progress: 0,
    tasksToday: 0,
    successRate: 0,
    avgResponseTime: "—",
    lastAction: "Pending deployment",
    lastActionTime: 0,
    scripture: "Numbers 10:2",
  },
  {
    id: "the-scout",
    name: "The Scout",
    avatar: "🔭",
    role: "Competitive Intelligence",
    department: "Intelligence",
    departmentColor: "#14B8A6",
    status: "planned",
    machine: "Solomon",
    deployWeek: 5,
    currentTask: "Deploying Weeks 5–6 — weekly competitor briefs via FB Ad Library MCP",
    progress: 0,
    tasksToday: 0,
    successRate: 0,
    avgResponseTime: "—",
    lastAction: "Pending deployment",
    lastActionTime: 0,
    scripture: "Numbers 13:16",
  },
  {
    id: "the-steward",
    name: "The Steward",
    avatar: "📊",
    role: "Financial Modeling",
    department: "Finance",
    departmentColor: "#6366F1",
    status: "planned",
    machine: "Solomon2",
    deployWeek: 7,
    currentTask: "Deploying Weeks 7–8 — 90-day cash flow forecast, zero-liquidation enforcement",
    progress: 0,
    tasksToday: 0,
    successRate: 0,
    avgResponseTime: "—",
    lastAction: "Pending deployment",
    lastActionTime: 0,
    scripture: "Matthew 25:23",
  },
  {
    id: "the-centurion",
    name: "The Centurion",
    avatar: "⚔️",
    role: "High-Ticket DM Sales",
    department: "Sales",
    departmentColor: "#EF4444",
    status: "planned",
    machine: "Solomon",
    deployWeek: 7,
    currentTask: "Deploying Weeks 7–8 — qualifies warm leads, routes to discovery calls",
    progress: 0,
    tasksToday: 0,
    successRate: 0,
    avgResponseTime: "—",
    lastAction: "Pending deployment",
    lastActionTime: 0,
    scripture: "Matthew 8:9",
  },
  {
    id: "the-steward-of-supply",
    name: "Steward of Supply",
    avatar: "📦",
    role: "Inventory Management",
    department: "Operations",
    departmentColor: "#84CC16",
    status: "planned",
    machine: "Solomon2",
    deployWeek: 9,
    currentTask: "Deploying Weeks 9–10 — Shopify inventory, demand forecast, reorder alerts",
    progress: 0,
    tasksToday: 0,
    successRate: 0,
    avgResponseTime: "—",
    lastAction: "Pending deployment",
    lastActionTime: 0,
    scripture: "Genesis 41:48",
  },
  {
    id: "the-ambassador",
    name: "The Ambassador",
    avatar: "🌐",
    role: "Affiliate + Influencer Outreach",
    department: "Partnerships",
    departmentColor: "#A78BFA",
    status: "planned",
    machine: "Solomon",
    deployWeek: 9,
    currentTask: "Deploying Weeks 9–10 — TikTok Shop creators, faith bloggers, affiliate program",
    progress: 0,
    tasksToday: 0,
    successRate: 0,
    avgResponseTime: "—",
    lastAction: "Pending deployment",
    lastActionTime: 0,
    scripture: "2 Corinthians 5:20",
  },
  {
    id: "the-cornerstone",
    name: "The Cornerstone",
    avatar: "🏛️",
    role: "Community Engine",
    department: "Community",
    departmentColor: "#34D399",
    status: "planned",
    machine: "Solomon",
    deployWeek: 9,
    currentTask: "Deploying Weeks 9–10 — BiohackingVille on Circle.so, 500 member target",
    progress: 0,
    tasksToday: 0,
    successRate: 0,
    avgResponseTime: "—",
    lastAction: "Pending deployment",
    lastActionTime: 0,
    scripture: "Psalm 118:22",
  },
  {
    id: "the-alchemist",
    name: "The Alchemist",
    avatar: "⚗️",
    role: "Product R&D Intelligence",
    department: "Innovation",
    departmentColor: "#FCD34D",
    status: "planned",
    machine: "Solomon2",
    deployWeek: 11,
    currentTask: "Deploying Weeks 11–12 — product opportunities from VOC + competitive intel",
    progress: 0,
    tasksToday: 0,
    successRate: 0,
    avgResponseTime: "—",
    lastAction: "Pending deployment",
    lastActionTime: 0,
    scripture: "Proverbs 8:12",
  },
];

// ─── ACTIVITY FEED (AIWorkforce live feed) ────────────────────────────────────

export const ACTIVITY_FEED = [
  { agent: "The Levite",  action: "Compliance gate LIVE — FastAPI endpoint operational on Solomon2",    time: 0,   icon: "⚖️" },
  { agent: "Solomon",     action: "Week 1 standing orders issued — compliance first, parallel tracks active", time: 1,  icon: "⚔️" },
  { agent: "The Levite",  action: "Forbidden terms database loaded for all 6 product lines",            time: 2,   icon: "⚖️" },
  { agent: "Solomon",     action: "Cold email domain purchase order: getexodusstrong.com et al",        time: 5,   icon: "⚔️" },
  { agent: "Solomon",     action: "Laurel Phase 1 active — 3 videos × $5/day = $15/day Video Views",   time: 10,  icon: "📱" },
  { agent: "Solomon",     action: "Red Wave Phase 1 initiated — PodMatch, MatchMaker.fm registrations", time: 15, icon: "🌊" },
  { agent: "Solomon",     action: "Warm list PROTECTED — Gate II active. 8,400 subs waiting.",         time: 20,  icon: "🔒" },
  { agent: "Solomon",     action: "FDA/FTC counsel search initiated — Hyman Phelps, Venable LLP",      time: 30,  icon: "⚖️" },
  { agent: "The Scribe",  action: "Scheduled for Week 2 deployment on Solomon2",                       time: 60,  icon: "📜" },
  { agent: "The Merchant",action: "Scheduled for Week 3 deployment on Solomon",                        time: 90,  icon: "🛒" },
];

// ─── REVENUE CASH EVENTS (Financials + Projects) ─────────────────────────────

export const CASH_EVENTS = [
  { week: "3+",   name: "The Merchant",        low: 2000,  high: 4000,  type: "monthly",   status: "upcoming", agent: "The Merchant" },
  { week: "5–6",  name: "⚡ Warm List Launch", low: 11000, high: 28000, type: "one-time",  status: "locked",   agent: "The Scribe + GHL", gate: "Gate II" },
  { week: "5+",   name: "Cold Email B2B",       low: 500,   high: 2000,  type: "monthly",   status: "upcoming", agent: "The Scribe + OpenClaw" },
  { week: "6+",   name: "Laurel Phase 3–4",     low: 2000,  high: 5000,  type: "monthly",   status: "upcoming", agent: "OpenClaw + The Oracle" },
  { week: "7+",   name: "Subscriptions",        low: 1000,  high: 3000,  type: "recurring", status: "upcoming", agent: "The Merchant" },
  { week: "7–8",  name: "Red Wave Phase 2",     low: 1000,  high: 5000,  type: "monthly",   status: "locked",   agent: "The Ambassador", gate: "Gate I" },
  { week: "5+",   name: "Funnel + Organic",     low: 3000,  high: 15000, type: "scaling",   status: "upcoming", agent: "The Oracle + The Trumpet" },
  { week: "10+",  name: "Affiliate Revenue",    low: 1000,  high: 5000,  type: "monthly",   status: "planned",  agent: "The Ambassador" },
  { week: "10+",  name: "$27 Challenge Guide",  low: 1000,  high: 3000,  type: "monthly",   status: "planned",  agent: "The Herald + Actovision" },
];

export const JUBILEE_TARGET    = 250000;  // 6-month conservative
export const MONTH_3_TARGET    = 70000;   // Month 3 conservative
export const CURRENT_REVENUE   = 0;       // Update weekly

// ─── PROJECTS (Projects component) ───────────────────────────────────────────

export const PROJECTS = [
  {
    name: "The Nehemiah Protocol",
    description: "Master execution plan — all brands, all agents, all revenue channels",
    phase: "Week 1 of 12",
    status: "active",
    color: "#C9A84C",
    completion: 8,
    owner: "Solomon + Rob",
  },
  {
    name: "AC Ascension Funnel",
    description: "$47 Book → OB → OTO1 ($67 H₂) → OTO2 (device) → $60/mo sub via Zipify OCU",
    phase: "Building",
    status: "in-progress",
    color: "#7B61FF",
    completion: 5,
    owner: "The Herald + Actovision",
  },
  {
    name: "The Levite — Compliance Gate",
    description: "FastAPI + 3-agent CrewAI crew. GREEN/YELLOW/RED verdict system on Solomon2",
    phase: "LIVE ✓",
    status: "complete",
    color: "#10B981",
    completion: 100,
    owner: "Solomon2",
  },
  {
    name: "Cold Email Infrastructure",
    description: "3 cold domains, SPF/DKIM/DMARC, Instantly warmup, 500+ B2B list",
    phase: "Week 1–4 Setup",
    status: "in-progress",
    color: "#2F80FF",
    completion: 10,
    owner: "OpenClaw + The Scribe",
  },
  {
    name: "Project Red Wave",
    description: "200+ media opportunities. Phase 1 (free) live. Phase 2 ($5K) locked behind Gate I.",
    phase: "Phase 1 Active",
    status: "in-progress",
    color: "#FF4EDB",
    completion: 15,
    owner: "Jay + The Ambassador",
  },
  {
    name: "Light Code Book",
    description: "Primary front-end product. $47. The Herald generating funnel copy.",
    phase: "In Production",
    status: "in-progress",
    color: "#F59E0B",
    completion: 40,
    owner: "Rob + The Herald",
  },
  {
    name: "FDA/FTC Regulatory Counsel",
    description: "Outreach to Hyman Phelps, Venable LLP, Goletti network referrals. Gate I.",
    phase: "Searching",
    status: "blocked",
    color: "#EF4444",
    completion: 5,
    owner: "Rob",
  },
  {
    name: "BiohackingVille Community",
    description: "Circle.so platform. Free tier only until 500+ engaged members. The Cornerstone.",
    phase: "Planned — Week 9",
    status: "planned",
    color: "#34D399",
    completion: 0,
    owner: "The Cornerstone",
  },
];

// ─── 24HR SCHEDULE (CEODashboard schedule view) ───────────────────────────────

export const SCHEDULE = [
  {
    shift: "MORNING", time: "6 AM – 12 PM", color: "#2F80FF",
    tasks: [
      { time: "6:00",  task: "The Watchman: daily intelligence brief delivered to Rob", dept: "Intelligence" },
      { time: "7:00",  task: "Cold email morning batch (domain warmup — 10–20/day)", dept: "Cold Email" },
      { time: "7:30",  task: "Solomon: review Levite compliance queue (YELLOW flags)", dept: "Compliance" },
      { time: "8:00",  task: "The Trumpet: publish daily social content via Carpe Diem", dept: "Social" },
      { time: "9:00",  task: "Red Wave Phase 1: podcast guest application follow-ups", dept: "Red Wave" },
      { time: "10:00", task: "Laurel Phase 1: monitor video view campaigns — check CPV", dept: "Paid Ads" },
      { time: "10:30", task: "The Scribe: process email sequence drafts (Levite scan)", dept: "Email" },
      { time: "11:00", task: "The Scout: weekly competitor brief (FB Ad Library)", dept: "Intelligence" },
    ],
  },
  {
    shift: "AFTERNOON", time: "12 PM – 6 PM", color: "#7B61FF",
    tasks: [
      { time: "12:00", task: "Cold email afternoon batch + list building (Apollo.io)", dept: "Cold Email" },
      { time: "12:30", task: "The Herald: funnel copy generation session", dept: "Copy" },
      { time: "1:00",  task: "Red Wave: faith network outreach batch (AccessMore, LifeAudio)", dept: "Red Wave" },
      { time: "2:00",  task: "The Multiplier: process Rob's pillar video → 10–15 assets", dept: "Content" },
      { time: "3:00",  task: "GHL pipeline review — cold email responses → booked calls", dept: "CRM" },
      { time: "4:00",  task: "The Shepherd: customer service queue + VOC analysis", dept: "Support" },
      { time: "5:00",  task: "The Merchant: cart recovery analysis + sequence tweaks", dept: "Revenue" },
      { time: "5:30",  task: "Laurel Phase 1: daily spend report → Telegram alert", dept: "Paid Ads" },
    ],
  },
  {
    shift: "EVENING", time: "6 PM – 12 AM", color: "#FF4EDB",
    tasks: [
      { time: "6:00",  task: "Cold email evening batch (warm audiences)", dept: "Cold Email" },
      { time: "6:30",  task: "The Centurion: DM qualification for hot leads", dept: "Sales" },
      { time: "7:00",  task: "Red Wave: social engagement with target show hosts", dept: "Red Wave" },
      { time: "8:00",  task: "The Oracle: A/B test analysis — offer-level first", dept: "CRO" },
      { time: "9:00",  task: "The Scout: new Red Wave target research", dept: "Intelligence" },
      { time: "10:00", task: "The Trumpet: queue tomorrow's content calendar", dept: "Social" },
      { time: "10:30", task: "Launch overnight Laurel Phase 1 ad monitoring", dept: "Paid Ads" },
      { time: "11:00", task: "The Watchman: daily report — leads, revenue, Levite flags", dept: "Intelligence" },
    ],
  },
  {
    shift: "OVERNIGHT", time: "12 AM – 6 AM", color: "#8A8F98",
    tasks: [
      { time: "12:00", task: "Cold email international batch", dept: "Cold Email" },
      { time: "12:30", task: "The Alchemist: VOC data → product R&D brief", dept: "Innovation" },
      { time: "1:00",  task: "The Scout: deep competitor + media target research", dept: "Intelligence" },
      { time: "2:00",  task: "List building + verification (NeverBounce)", dept: "Cold Email" },
      { time: "3:00",  task: "The Multiplier: async content repurposing queue", dept: "Content" },
      { time: "4:00",  task: "The Steward: 90-day cash flow model update", dept: "Finance" },
      { time: "4:30",  task: "Overnight ad monitoring — Laurel Phase 1 alerts", dept: "Paid Ads" },
      { time: "5:00",  task: "The Watchman: morning briefing prep for Rob at 6:00 AM", dept: "Intelligence" },
    ],
  },
];

// ─── FINANCIALS ───────────────────────────────────────────────────────────────

export const FINANCIALS = {
  weeklyAdBudget: 105,      // $15/day × 7
  monthlyAdTarget: 450,     // Phase 1 investment
  projectedMonth3: { low: 60000,  high: 80000  },
  projectedMonth6: { low: 250000, high: 400000 },
  warmListProjection: {
    at2pct:  11300,
    at3pct:  17000,
    at5pct:  28000,
  },
  currentMRR: 0,
  currentCash: 0,           // Update as revenue comes in
};
